services:
  # 编译环境
  service:
    image: ${PRODUCT_IMAGE}
    restart: always
    network_mode: "host"
    privileged: true
    environment:
      - LD_LIBRARY_PATH=/workspace
    volumes:
      - /const:/const
      - /user_profiles:/user_profiles
      - /corefile:/corefile
    command: ./main
    ports:
      - "50051:50051"

  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - TZ=CST-8
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
    command:
      - "--memory.max-traces=50000"
    deploy:
      resources:
        limits:
          memory: 1000M
    restart: unless-stopped
