
FROM twelfive5t/server_builder:latest

USER root

# 更新包索引
RUN apt update

# 其他工具
RUN apt install -y \
    vim htop

RUN apt install -y zsh git curl wget \
    && chsh -s $(which zsh) \
    && sh -c "$(wget -O- https://install.ohmyz.sh/)"

RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k \
    && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions \
    && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting \
    && git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search \
    && git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-completions \
    && git clone https://github.com/MichaelAquilina/zsh-you-should-use.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/you-should-use \
    && git clone https://github.com/sunlei/zsh-ssh ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-ssh

RUN curl -o ~/.p10k.zsh https://raw.githubusercontent.com/Twelfive5t/EnvironmentDocument/main/Linux/File/.p10k.zsh \
    && curl -o ~/.zshrc https://raw.githubusercontent.com/Twelfive5t/EnvironmentDocument/main/Linux/File/.zshrc \
    && curl -o ~/.vimrc https://raw.githubusercontent.com/Twelfive5t/EnvironmentDocument/main/Linux/File/.vimrc

WORKDIR /workspace
