// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server_messages.proto

#include "server_messages.pb.h"
#include "server_messages.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ServerMessages {

static const char* ServerMessagesService_method_names[] = {
  "/ServerMessages.ServerMessagesService/CheckOnline",
};

std::unique_ptr< ServerMessagesService::Stub> ServerMessagesService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServerMessagesService::Stub> stub(new ServerMessagesService::Stub(channel, options));
  return stub;
}

ServerMessagesService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CheckOnline_(ServerMessagesService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ServerMessagesService::Stub::CheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::ServerMessages::CheckOnlineReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ServerMessages::CheckOnlineRequest, ::ServerMessages::CheckOnlineReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CheckOnline_, context, request, response);
}

void ServerMessagesService::Stub::async::CheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest* request, ::ServerMessages::CheckOnlineReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ServerMessages::CheckOnlineRequest, ::ServerMessages::CheckOnlineReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckOnline_, context, request, response, std::move(f));
}

void ServerMessagesService::Stub::async::CheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest* request, ::ServerMessages::CheckOnlineReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckOnline_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ServerMessages::CheckOnlineReply>* ServerMessagesService::Stub::PrepareAsyncCheckOnlineRaw(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ServerMessages::CheckOnlineReply, ::ServerMessages::CheckOnlineRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CheckOnline_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ServerMessages::CheckOnlineReply>* ServerMessagesService::Stub::AsyncCheckOnlineRaw(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckOnlineRaw(context, request, cq);
  result->StartCall();
  return result;
}

ServerMessagesService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerMessagesService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerMessagesService::Service, ::ServerMessages::CheckOnlineRequest, ::ServerMessages::CheckOnlineReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerMessagesService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ServerMessages::CheckOnlineRequest* req,
             ::ServerMessages::CheckOnlineReply* resp) {
               return service->CheckOnline(ctx, req, resp);
             }, this)));
}

ServerMessagesService::Service::~Service() {
}

::grpc::Status ServerMessagesService::Service::CheckOnline(::grpc::ServerContext* context, const ::ServerMessages::CheckOnlineRequest* request, ::ServerMessages::CheckOnlineReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ServerMessages

