// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_messages.proto

#include "server_messages.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ServerMessages {
PROTOBUF_CONSTEXPR CheckOnlineRequest::CheckOnlineRequest(
    ::_pbi::ConstantInitialized) {}
struct CheckOnlineRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckOnlineRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckOnlineRequestDefaultTypeInternal() {}
  union {
    CheckOnlineRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckOnlineRequestDefaultTypeInternal _CheckOnlineRequest_default_instance_;
PROTOBUF_CONSTEXPR CheckOnlineReply::CheckOnlineReply(
    ::_pbi::ConstantInitialized) {}
struct CheckOnlineReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckOnlineReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckOnlineReplyDefaultTypeInternal() {}
  union {
    CheckOnlineReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckOnlineReplyDefaultTypeInternal _CheckOnlineReply_default_instance_;
}  // namespace ServerMessages
static ::_pb::Metadata file_level_metadata_server_5fmessages_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_server_5fmessages_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_server_5fmessages_2eproto = nullptr;

const uint32_t TableStruct_server_5fmessages_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ServerMessages::CheckOnlineRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ServerMessages::CheckOnlineReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ServerMessages::CheckOnlineRequest)},
  { 6, -1, -1, sizeof(::ServerMessages::CheckOnlineReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ServerMessages::_CheckOnlineRequest_default_instance_._instance,
  &::ServerMessages::_CheckOnlineReply_default_instance_._instance,
};

const char descriptor_table_protodef_server_5fmessages_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025server_messages.proto\022\016ServerMessages\""
  "\024\n\022CheckOnlineRequest\"\022\n\020CheckOnlineRepl"
  "y2n\n\025ServerMessagesService\022U\n\013CheckOnlin"
  "e\022\".ServerMessages.CheckOnlineRequest\032 ."
  "ServerMessages.CheckOnlineReply\"\000B\006\242\002\003HL"
  "Wb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_server_5fmessages_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_server_5fmessages_2eproto = {
    false, false, 209, descriptor_table_protodef_server_5fmessages_2eproto,
    "server_messages.proto",
    &descriptor_table_server_5fmessages_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_server_5fmessages_2eproto::offsets,
    file_level_metadata_server_5fmessages_2eproto, file_level_enum_descriptors_server_5fmessages_2eproto,
    file_level_service_descriptors_server_5fmessages_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_server_5fmessages_2eproto_getter() {
  return &descriptor_table_server_5fmessages_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_server_5fmessages_2eproto(&descriptor_table_server_5fmessages_2eproto);
namespace ServerMessages {

// ===================================================================

class CheckOnlineRequest::_Internal {
 public:
};

CheckOnlineRequest::CheckOnlineRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:ServerMessages.CheckOnlineRequest)
}
CheckOnlineRequest::CheckOnlineRequest(const CheckOnlineRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  CheckOnlineRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ServerMessages.CheckOnlineRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CheckOnlineRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CheckOnlineRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata CheckOnlineRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5fmessages_2eproto_getter, &descriptor_table_server_5fmessages_2eproto_once,
      file_level_metadata_server_5fmessages_2eproto[0]);
}

// ===================================================================

class CheckOnlineReply::_Internal {
 public:
};

CheckOnlineReply::CheckOnlineReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:ServerMessages.CheckOnlineReply)
}
CheckOnlineReply::CheckOnlineReply(const CheckOnlineReply& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  CheckOnlineReply* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ServerMessages.CheckOnlineReply)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CheckOnlineReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CheckOnlineReply::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata CheckOnlineReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5fmessages_2eproto_getter, &descriptor_table_server_5fmessages_2eproto_once,
      file_level_metadata_server_5fmessages_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ServerMessages
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ServerMessages::CheckOnlineRequest*
Arena::CreateMaybeMessage< ::ServerMessages::CheckOnlineRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ServerMessages::CheckOnlineRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ServerMessages::CheckOnlineReply*
Arena::CreateMaybeMessage< ::ServerMessages::CheckOnlineReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ServerMessages::CheckOnlineReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
