// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server_messages.proto
#ifndef GRPC_server_5fmessages_2eproto__INCLUDED
#define GRPC_server_5fmessages_2eproto__INCLUDED

#include "server_messages.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ServerMessages {

class ServerMessagesService final {
 public:
  static constexpr char const* service_full_name() {
    return "ServerMessages.ServerMessagesService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::ServerMessages::CheckOnlineReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerMessages::CheckOnlineReply>> AsyncCheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerMessages::CheckOnlineReply>>(AsyncCheckOnlineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerMessages::CheckOnlineReply>> PrepareAsyncCheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerMessages::CheckOnlineReply>>(PrepareAsyncCheckOnlineRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest* request, ::ServerMessages::CheckOnlineReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest* request, ::ServerMessages::CheckOnlineReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ServerMessages::CheckOnlineReply>* AsyncCheckOnlineRaw(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ServerMessages::CheckOnlineReply>* PrepareAsyncCheckOnlineRaw(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::ServerMessages::CheckOnlineReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerMessages::CheckOnlineReply>> AsyncCheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerMessages::CheckOnlineReply>>(AsyncCheckOnlineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerMessages::CheckOnlineReply>> PrepareAsyncCheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerMessages::CheckOnlineReply>>(PrepareAsyncCheckOnlineRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest* request, ::ServerMessages::CheckOnlineReply* response, std::function<void(::grpc::Status)>) override;
      void CheckOnline(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest* request, ::ServerMessages::CheckOnlineReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ServerMessages::CheckOnlineReply>* AsyncCheckOnlineRaw(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ServerMessages::CheckOnlineReply>* PrepareAsyncCheckOnlineRaw(::grpc::ClientContext* context, const ::ServerMessages::CheckOnlineRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CheckOnline_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CheckOnline(::grpc::ServerContext* context, const ::ServerMessages::CheckOnlineRequest* request, ::ServerMessages::CheckOnlineReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CheckOnline() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CheckOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckOnline(::grpc::ServerContext* /*context*/, const ::ServerMessages::CheckOnlineRequest* /*request*/, ::ServerMessages::CheckOnlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckOnline(::grpc::ServerContext* context, ::ServerMessages::CheckOnlineRequest* request, ::grpc::ServerAsyncResponseWriter< ::ServerMessages::CheckOnlineReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CheckOnline<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CheckOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CheckOnline() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ServerMessages::CheckOnlineRequest, ::ServerMessages::CheckOnlineReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ServerMessages::CheckOnlineRequest* request, ::ServerMessages::CheckOnlineReply* response) { return this->CheckOnline(context, request, response); }));}
    void SetMessageAllocatorFor_CheckOnline(
        ::grpc::MessageAllocator< ::ServerMessages::CheckOnlineRequest, ::ServerMessages::CheckOnlineReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ServerMessages::CheckOnlineRequest, ::ServerMessages::CheckOnlineReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CheckOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckOnline(::grpc::ServerContext* /*context*/, const ::ServerMessages::CheckOnlineRequest* /*request*/, ::ServerMessages::CheckOnlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckOnline(
      ::grpc::CallbackServerContext* /*context*/, const ::ServerMessages::CheckOnlineRequest* /*request*/, ::ServerMessages::CheckOnlineReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CheckOnline<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CheckOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CheckOnline() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CheckOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckOnline(::grpc::ServerContext* /*context*/, const ::ServerMessages::CheckOnlineRequest* /*request*/, ::ServerMessages::CheckOnlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CheckOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CheckOnline() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CheckOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckOnline(::grpc::ServerContext* /*context*/, const ::ServerMessages::CheckOnlineRequest* /*request*/, ::ServerMessages::CheckOnlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckOnline(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CheckOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CheckOnline() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CheckOnline(context, request, response); }));
    }
    ~WithRawCallbackMethod_CheckOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckOnline(::grpc::ServerContext* /*context*/, const ::ServerMessages::CheckOnlineRequest* /*request*/, ::ServerMessages::CheckOnlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckOnline(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CheckOnline() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ServerMessages::CheckOnlineRequest, ::ServerMessages::CheckOnlineReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ServerMessages::CheckOnlineRequest, ::ServerMessages::CheckOnlineReply>* streamer) {
                       return this->StreamedCheckOnline(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CheckOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckOnline(::grpc::ServerContext* /*context*/, const ::ServerMessages::CheckOnlineRequest* /*request*/, ::ServerMessages::CheckOnlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckOnline(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ServerMessages::CheckOnlineRequest,::ServerMessages::CheckOnlineReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CheckOnline<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CheckOnline<Service > StreamedService;
};

}  // namespace ServerMessages


#endif  // GRPC_server_5fmessages_2eproto__INCLUDED
