apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    isDefault: true
    jsonData:
      tracesToLogsV2:               # Trace 视图中关联 Loki 日志，时间窗口前后各扩展 5 分钟
        datasourceUid: loki
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        tags:
          - key: service.name
            value: service_name
        filterByTraceID: false
        filterBySpanID: false
        customQuery: false
      tracesToMetrics:              # Trace 视图中跳转到对应 Prometheus 指标
        datasourceUid: prometheus
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        tags:
          - key: service.name
            value: service_name
        queries:
          - name: Request rate
            query: sum(rate(rpc_server_requests_total{$$__tags}[5m]))
      nodeGraph:
        enabled: true               # 开启服务拓扑图
      serviceMap:
        datasourceUid: 'prometheus' # 服务地图数据来自 Prometheus 中的 span metrics
      search:
        hide: false
      lokiSearch:
        datasourceUid: 'loki'       # Trace 搜索时同时搜索 Loki 日志
